version: "3.9"
services:
  miner:
    build: .
    command: bitcoind -connect=node1:8332 -connect=node2:8332
  node1:
    build: .
    command: bitcoind -connect=miner:8332 -connect=node2:8332
  node2:
    build: .
    command: bitcoind -connect=miner:8332 -connect=node1:8332